sudo: false

language: python

install:
  - pip install -r test-requirements.txt

matrix:
  include:
  - name: "2.7 Lint checks"
    python: "2.7"
    script:
      - tox -e flake8
  - name: "3.4 Lint checks"
    python: "3.4"
    script:
      - tox -e flake8
  - name: "2.7 Unit tests"
    python: "2.7"
    script:
      - echo "skipped due to empty testcasses"
  - name: "3.4 Unit tests"
    python: "3.4"
    script:
      - echo "skipped due to empty testcasses"
  - name: "2.7 Functional tests"
    python: "2.7"
    script:
      - echo "skipped due to empty testcasses"
  - name: "3.4 Functional tests"
    python: "3.4"
    script:
      - echo "skipped due to empty testcasses"
  - name: "Build and Publish"
    python: "3.4"
    script:
      - echo Publishing.....
    before_deploy:
      - python setup.py sdist        
    deploy:
      provider: releases
      file_glob: true
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      file: dist/*.tar.gz
      on:
        tags: true

