sudo: false

language: python

python:
  - 3.4

install:
  - pip install -r test-requirements.txt

branches:
  only:
    - master

jobs:
  include:
    - stage: lint checks
      script:
        - tox -e flake8
      python:
        - 2.7
        - 3.4
    - stage: unit tests
      script:
        - echo skipped
      python:
        - 2.7
        - 3.4
    - stage: functional tests
      script:
        - echo skipped
      python:
        - 2.7
        - 3.4
    - stage: build and publish release
      script: 
        - echo publishing
      before_deploy:        
        - python setup.py sdist
      deploy:
        provider: releases
        api_key: 23213457abab4ba6fb24aac98773c5d17cf6233d
        skip_cleanup: true
        file: dist/*.tar.gz
