sudo: false

language: python

install:
  - pip install -r test-requirements.txt

matrix:
  include:
  - name: "2.7 Lint checks"
    python: "2.7"
    script:
      - tox -e flake8
  - name: "3.5 Lint checks"
    python: "3.5"
    script:
      - tox -e flake8
  - name: "2.7 Unit tests"
    python: "2.7"
    script:
      - echo "skipped due to empty testcasses"
  - name: "3.5 Unit tests"
    python: "3.5"
    script:
      - echo "skipped due to empty testcasses"
  - name: "2.7 Functional tests"
    python: "2.7"
    script:
      - tox -e functional
  - name: "3.5 Functional tests"
    python: "3.5"
    script:
      - tox -e functional
  - name: "Publish to github"
    python: "3.5"
    script:
      - echo "Publishing to github"
    before_deploy:
      - python setup.py sdist        
    deploy:
      provider: releases
      file_glob: true
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      file: dist/*.tar.gz
      on:
        tags: true
  - name: "Publish to PyPi"
    python: "3.5"
    script:
      - echo "Publishing to Pypi"
    deploy:
      provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true
